///|
pub extend Failure with Eq::{equal, not_equal}

///|
pub extend Failure with @debug.Debug::{to_repr}

///|
pub extend MessageType with Eq::{equal, not_equal}

///|
pub extend MessageType with @debug.Debug::{to_repr}

///|
pub extend Method with Eq::{equal, not_equal}

///|
pub extend Method with @debug.Debug::{to_repr}

///|
pub extend Code with Eq::{equal, not_equal}

///|
pub extend Code with @debug.Debug::{to_repr}

///|
pub extend CoapOption with Eq::{equal, not_equal}

///|
pub extend CoapOption with @debug.Debug::{to_repr}

///|
pub extend Message with Eq::{equal, not_equal}

///|
pub extend Message with @debug.Debug::{to_repr}

///|
pub extend Limits with Eq::{equal, not_equal}

///|
pub extend Limits with @debug.Debug::{to_repr}

///|
pub extend Request with Eq::{equal, not_equal}

///|
pub extend Request with @debug.Debug::{to_repr}

///|
pub extend Response with Eq::{equal, not_equal}

///|
pub extend Response with @debug.Debug::{to_repr}
